name: Sync
on:
  workflow_dispatch: # on button click
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Sync repo to branch
      uses: repo-sync/github-sync@v2
      with:
        source_repo: https://github.com/arturkasperek/test-repo-original.git
        source_branch: main
        destination_branch: upstream
        github_token: ${{ secrets.PAT }}
