name: Sync
on:
  workflow_dispatch: # on button click
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "https://github.com/arturkasperek/test-repo-original.git"
        source_branch: "main"
        destination_repo: "arturkasperek/test-repo-fork"
        destination_branch: "main"
